In [3]:
from dotenv import load_dotenv
load_dotenv(".env")

from sklearn.datasets import load_iris
import numpy as np
import numpyai_dashboard as npi

from rich.console import Console

In [4]:
c = Console() 

In [5]:
iris = load_iris()
X, y = iris.data, iris.target
print(isinstance(X, np.ndarray) and isinstance(y, np.ndarray))

True


In [6]:
sess = npi.NumpyAISession([X, y], verbose=False)
diag = npi.Diagnosis(sess)

In [7]:
steps = diag.steps(task="Give me the exact and pithy steps to decide which machine learning model to use. Don't go into the Machine Learning side, rather use simple data-analysis. You should not give more than seven steps.")

────────────────────────────────────────────────── LLM Response ───────────────────────────────────────────────────

╭────────────────────────────────────────────── Data Analysis Steps ──────────────────────────────────────────────╮
│ [ "1. Confirm Data Roles and Structure: Identify arr1 as the feature matrix and arr2 as the target vector. Use  │
│ NumPy's shape and dtype to verify dimensions (e.g., (150, 4) features, (150,) target) and data types. This      │
│ diagnostic step confirms a supervised learning context and the number of samples, features, and the target's    │
│ nature (continuous vs. discrete).", "2. Analyze Target Variable Distribution: Use unique and bincount on arr2   │
│ to determine the distinct classes (0, 1, 2) and their frequencies. This step diagnoses class balance; if highly │
│ imbalanced, it suggests that models robust to imbalance or specific resampling techniques might be required     │
│ during model training.", "3. Compute Basic Feature Statistics: Calculate mean, median, std, min, max for each   │
│ column (feature) of arr1 using axis=0. This provides a summary of each feature's central tendency and           │
│ dispersion. Widely varying scales between features (e.g., large differences in mean or max) would diagnose a    │
│ need for feature scaling (normalization or standardization) as a preprocessing step for many models.", "4.      │
│ Assess Feature Distributions and Outliers: Further examine feature spread using percentile to calculate         │
│ interquartile ranges (IQR) for each feature in arr1. Compare these with min and max values from Step 3 to       │
│ identify potential outliers. Diagnosis of skewed distributions or significant outliers indicates that some      │
│ models might be sensitive, suggesting either robust models or data transformations (e.g., log transform) or     │
│ outlier handling.", "5. Examine Feature Separability per Class: Group arr1 by the classes in arr2 and compute   │
│ the mean and std for each feature within each class. This is a crucial diagnostic step: if feature              │
│ means/distributions are clearly separated across different classes, simpler linear models might be effective.   │
│ Significant overlap, conversely, suggests that more complex, non-linear models might be necessary to            │
│ distinguish between classes.", "6. Evaluate Inter-Feature Correlation: Compute the corrcoef for all features in │
│ arr1. High absolute correlation values (e.g., >0.7) between features indicate multicollinearity. This diagnoses │
│ potential issues for certain linear models, suggesting that dimensionality reduction or feature selection might │
│ be beneficial, while tree-based models are generally less affected." ]                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [9]:
for step in steps:
    try:
        vals = sess.chat(step)
        print(vals)
    except:
        c.print(f"The following step failed: {step}")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 1. **Confirm Data Roles and Structure:** Identify `arr1` as the feature matrix and `arr2` as the target  │
│ vector. Use NumPy's `shape` and `dtype` to verify dimensions (e.g., (150, 4) features, (150,) target) and data  │
│ types. This diagnostic step confirms a supervised learning context and the number of samples, features, and the │
│ target's nature (continuous vs. discrete).                                                                      │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

{'arr1_shape': (150, 4), 'arr1_dtype': dtype('float64'), 'arr2_shape': (150,), 'arr2_dtype': dtype('int64')}


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 2. **Analyze Target Variable Distribution:** Use `unique` and `bincount` on `arr2` to determine the      │
│ distinct classes (0, 1, 2) and their frequencies. This step diagnoses class balance; if highly imbalanced, it   │
│ suggests that models robust to imbalance or specific resampling techniques might be required during model       │
│ training.                                                                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

{'classes': [0, 1, 2], 'frequencies': [50, 50, 50]}


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 3. **Compute Basic Feature Statistics:** Calculate `mean`, `median`, `std`, `min`, `max` for each column │
│ (feature) of `arr1` using `axis=0`. This provides a summary of each feature's central tendency and dispersion.  │
│ Widely varying scales between features (e.g., large differences in `mean` or `max`) would diagnose a need for   │
│ feature scaling (normalization or standardization) as a preprocessing step for many models.                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

{'mean': array([5.84333333, 3.05733333, 3.758     , 1.19933333]), 'median': array([5.8 , 3.  , 4.35, 1.3 ]), 'std': array([0.82530129, 0.43441097, 1.75940407, 0.75969263]), 'min': array([4.3, 2. , 1. , 0.1]), 'max': array([7.9, 4.4, 6.9, 2.5])}


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 4. **Assess Feature Distributions and Outliers:** Further examine feature spread using `percentile` to   │
│ calculate interquartile ranges (IQR) for each feature in `arr1`. Compare these with `min` and `max` values from │
│ Step 3 to identify potential outliers. Diagnosis of skewed distributions or significant outliers indicates that │
│ some models might be sensitive, suggesting either robust models or data transformations (e.g., log transform)   │
│ or outlier handling.                                                                                            │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

{'iqr': array([1.3, 0.5, 3.5, 1.5]), 'min': array([4.3, 2. , 1. , 0.1]), 'max': array([7.9, 4.4, 6.9, 2.5]), 'q1': array([5.1, 2.8, 1.6, 0.3]), 'q3': array([6.4, 3.3, 5.1, 1.8])}


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 5. **Examine Feature Separability per Class:** Group `arr1` by the classes in `arr2` and compute the     │
│ `mean` and `std` for each feature *within each class*. This is a crucial diagnostic step: if feature            │
│ means/distributions are clearly separated across different classes, simpler linear models might be effective.   │
│ Significant overlap, conversely, suggests that more complex, non-linear models might be necessary to            │
│ distinguish between classes.                                                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

{'class_0': {'mean': array([5.006, 3.428, 1.462, 0.246]), 'std': array([0.34894699, 0.37525458, 0.17191859, 0.10432641])}, 'class_1': {'mean': array([5.936, 2.77 , 4.26 , 1.326]), 'std': array([0.51098337, 0.31064449, 0.46518813, 0.19576517])}, 'class_2': {'mean': array([6.588, 2.974, 5.552, 2.026]), 'std': array([0.62948868, 0.31925538, 0.54634787, 0.27188968])}}


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 6. **Evaluate Inter-Feature Correlation:** Compute the `corrcoef` for all features in `arr1`. High       │
│ absolute correlation values (e.g., >0.7) between features indicate multicollinearity. This diagnoses potential  │
│ issues for certain linear models, suggesting that dimensionality reduction or feature selection might be        │
│ beneficial, while tree-based models are generally less affected.                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
